version: "3"
services:
  web:
    image: sikii/pic_online
    container_name: pic_online
    hostname: pic_online
    # 如果遇到文件权限问题，手动指定 uid，gid 启动即可
    # UID=${UID} GID=${GID} docker-compose up
    # user: "${UID}:${GID}"
    restart: unless-stopped
    # network_mode: host
    logging:
      driver: json-file
      options:
        max-size: 1m
    volumes:
      # - ./data:/pic/data
      # 图片
      - ./data/images:/pic/data/images
      # 视频
      - ./data/video:/pic/data/video
      # 缓存
      - ./data/cache:/pic/data/cache
    ports:
      - 8089:8089
    environment:
      # 修改成实际的地址或域名, host 模式和 bridge 模式直接填宿主机 ip 即可
      # 如果你有 dns.he.net 的 ddns 域名, 可以尝试在 host 模式下将 MOLECULER_DDNS_ENABLE 设置为 true
      # ddns 的认证 key 需要设置成和域名一致.
      # 服务会自动从 192, 172, 10 网段找到第一个符合要求的 ip, 并更新 ddns
      - NAS_DOMAIN="127.0.0.1"
      # - PIC_BASE_DIR=/pic/data
      # 限定服务的监听地址, 默认 0.0.0.0
      # - MOLECULER_IP="0.0.0.0"
      # - MOLECULER_PORT=8089
      - MOLECULER_DDNS_ENABLE=false
      # SSL
      # - MOLECULER_HTTPS_CERT="/pic/data/ssl/nas.baidu.com/fullchain.cer"
      # - MOLECULER_HTTPS_KEY="/pic/data/ssl/nas.baidu.com/key.key"
      # 以下内容一般不需要修改
      # - PIC_DIR=$PIC_BASE_DIR/images
      # - VIDEO_DIR=$PIC_BASE_DIR/video
      # - PIC_POSTER_DIR=$PIC_BASE_DIR/cache
      # 图片地址前缀, 最后的 图片/视频 地址由 前缀 和 PIC_DIR/VIDEO_DIR 到 PIC_BASE_DIR 的相对路径组成
      # - PIC_PREFIX=http://$NAS_DOMAIN:$MOLECULER_PORT
    # entrypoint: tail -f /pic/App.js
