POST http://localhost:3000/public/file/pic_map
Content-Type: application/json

{
  "nodeKey": 1
}

###
POST http://localhost:3000/limit/user/login
Content-Type: application/json

{
  "name": "user",
  "password": "user"
}
